/**
 * Session management using database-backed tokens.
 *
 * Sessions are stored in the sessions table and sent to clients
 * as HTTP-only, Secure, SameSite=Strict cookies.
 *
 * Token format: UUID v4 (generated by crypto.randomUUID()).
 */

import { eq, and, gt } from 'drizzle-orm';
import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';
import { sessions, users, workspaceMembers } from '@copilot/types/database';
import type { PublicUser } from '@copilot/types';
import type { workspaceMemberRoleEnum } from '@copilot/types/database';

// Session duration: 7 days
const SESSION_DURATION_MS = 7 * 24 * 60 * 60 * 1000;

// Cookie name
export const SESSION_COOKIE_NAME = 'copilot_session';

/**
 * Create a new session for a user.
 * Returns the session token and expiration date.
 */
export async function createSession(
  db: PostgresJsDatabase,
  userId: string
): Promise<{ token: string; expiresAt: Date }> {
  const token = crypto.randomUUID();
  const expiresAt = new Date(Date.now() + SESSION_DURATION_MS);

  await db.insert(sessions).values({
    userId,
    token,
    expiresAt,
  });

  return { token, expiresAt };
}

/**
 * Validate a session token. Returns the user (safe fields only) or null.
 * Automatically deletes expired sessions.
 */
export async function validateSession(
  db: PostgresJsDatabase,
  token: string
): Promise<PublicUser | null> {
  const now = new Date();

  // Find active (non-expired) session
  const [session] = await db
    .select()
    .from(sessions)
    .where(and(eq(sessions.token, token), gt(sessions.expiresAt, now)))
    .limit(1);

  if (!session) {
    // Clean up expired session if it exists
    await db.delete(sessions).where(eq(sessions.token, token));
    return null;
  }

  // Fetch user (never return passwordHash)
  const [user] = await db
    .select({
      id: users.id,
      email: users.email,
      name: users.name,
      avatarUrl: users.avatarUrl,
      emailVerified: users.emailVerified,
      createdAt: users.createdAt,
    })
    .from(users)
    .where(eq(users.id, session.userId))
    .limit(1);

  if (!user) {
    // User was deleted; clean up orphaned session
    await db.delete(sessions).where(eq(sessions.id, session.id));
    return null;
  }

  return user as PublicUser;
}

/**
 * Delete a session (logout).
 */
export async function deleteSession(
  db: PostgresJsDatabase,
  token: string
): Promise<void> {
  await db.delete(sessions).where(eq(sessions.token, token));
}

/**
 * Delete all sessions for a user (logout from all devices).
 */
export async function deleteAllUserSessions(
  db: PostgresJsDatabase,
  userId: string
): Promise<void> {
  await db.delete(sessions).where(eq(sessions.userId, userId));
}

/**
 * Check if a user is a member of a workspace and return their role.
 */
export async function getWorkspaceMembership(
  db: PostgresJsDatabase,
  userId: string,
  workspaceId: string
): Promise<{ role: string } | null> {
  const [member] = await db
    .select({ role: workspaceMembers.role })
    .from(workspaceMembers)
    .where(
      and(
        eq(workspaceMembers.userId, userId),
        eq(workspaceMembers.workspaceId, workspaceId)
      )
    )
    .limit(1);

  if (!member || !member.role) return null;
  return { role: member.role };
}

// Role hierarchy: owner > admin > member > viewer
const ROLE_HIERARCHY: Record<string, number> = {
  owner: 4,
  admin: 3,
  member: 2,
  viewer: 1,
};

/**
 * Check if a user's role meets the minimum required role.
 */
export function hasMinimumRole(userRole: string, requiredRole: string): boolean {
  return (ROLE_HIERARCHY[userRole] ?? 0) >= (ROLE_HIERARCHY[requiredRole] ?? 0);
}
